-- Copie locale des députés (projet site) + suivi anonyme des clics d'envoi.
-- Écriture des députés : service_role uniquement (Edge Function de synchro).
-- Lecture des députés : publique (adresses parlementaires publiques).
-- Clics : insertion publique uniquement, aucune lecture côté client.

CREATE TABLE public.deputes (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	nom text NOT NULL,
	circonscription text NOT NULL,
	email text NOT NULL,
	actif boolean NOT NULL DEFAULT true,
	CONSTRAINT deputes_email_key UNIQUE (email)
);

CREATE TABLE public.evenements_clics (
	id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	bouton_clique text NOT NULL,
	depute_id bigint NOT NULL REFERENCES public.deputes (id) ON DELETE RESTRICT,
	date_creation timestamptz NOT NULL DEFAULT now(),
	CONSTRAINT evenements_clics_bouton_clique_check
		CHECK (bouton_clique IN ('mailto', 'gmail', 'outlook', 'copier'))
);

CREATE INDEX evenements_clics_depute_id_idx ON public.evenements_clics (depute_id);
CREATE INDEX evenements_clics_date_creation_idx ON public.evenements_clics (date_creation);

ALTER TABLE public.deputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evenements_clics ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Lecture publique des deputes"
	ON public.deputes
	FOR SELECT
	TO anon, authenticated
	USING (true);

-- Write-only : INSERT autorisé, pas de SELECT / UPDATE / DELETE pour anon ni authenticated.
CREATE POLICY "Insertion publique des evenements_clics"
	ON public.evenements_clics
	FOR INSERT
	TO anon, authenticated
	WITH CHECK (true);

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

REVOKE ALL ON TABLE public.deputes FROM anon, authenticated, PUBLIC;
GRANT SELECT ON TABLE public.deputes TO anon, authenticated;
GRANT ALL ON TABLE public.deputes TO service_role;

REVOKE ALL ON TABLE public.evenements_clics FROM anon, authenticated, PUBLIC;
GRANT INSERT ON TABLE public.evenements_clics TO anon, authenticated;
GRANT ALL ON TABLE public.evenements_clics TO service_role;

GRANT USAGE, SELECT ON SEQUENCE public.evenements_clics_id_seq TO anon, authenticated, service_role;
GRANT USAGE, SELECT ON SEQUENCE public.deputes_id_seq TO service_role;
